### ISSUE TITLE
Discrepancy between Java examples.

### ISSUE THREAD

**Issue by XerTheSquirrel** [iopipe/examples#18]
There is a discrepency between the Java examples. `PlainHello` uses `Map<String, String>` for input while `Hello` and `ManualHello` use `String`. It was originally `String` but was changed to `Map<String, String>`, but `Hello` and `ManualHello` were changed back to `String`. So at least for the hello examples, do we want valid input to be:

`String`:
```
"Stephanie"
```

or `Map<String, String>`:
```
{
    "name": "Stephanie"
}
```

?

**Comment by XerTheSquirrel** [comment]
Okay, so after talking with @pselle on Slack. She went back to using `String` so that the examples could be executed by CloudWatch, we additionally discussed `PlainHello` and we have decided that this baseline example is not really needed so I will delete it in a PR.

**Comment by pselle** [comment]
Clarifying that I went to `Map`, not `String`, for the notes :)
