### ISSUE TITLE
TypeScript Example

### ISSUE THREAD

**Issue by fastfiveoh** [iopipe/examples#34]
We need to document a quick example of the correct way to use IOpipe with typescript

**Comment by MikeBlair** [comment]
This would be helpful for our team.

**Comment by javonharper** [comment]
We now provide some TypeScript definitions through [DefinitelyTyped](An open source repository of popular TypeScript definitions). Ours can be found at [types/iopipe__iopipe](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/iopipe__iopipe) and examples can be found in [typescript.ts](https://github.com/iopipe/examples/blob/master/node/typescript.ts).
